spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TEST_RDS}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  social:
    kakao:
      client_id: ${KAKAO_CLIENT_ID}
      redirect: http:loaclhost:3000/oauth
      url:
        login: https://kauth.kakao.com/oauth/authorize  # 로그인 진행 사이트
        token: https://kauth.kakao.com/oauth/token  # access token을 발급 받는  url , 필요한 정보를 담아 보내야 함
        profile: https://kapi.kakao.com/v2/user/me  # Access Token을 통해 정보를 받는 url

    google:
      client_id: MaLmA8dihBCzDqsfr0iY
      client_secret: VIlICBy6vh
      redirect: http://localhost:8080/login/oauth2/code/google
      url:
        login: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo

    naver:
      client_id: MaLmA8dihBCzDqsfr0iY
      client_secret: VIlICBy6vh
      redirect: http://localhost:8080/social/login/naver
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me

cors:
  origin: http://localhost:3000